project:
  type: website

website:
  title: |
    Arte, Sociedade e\
    Interpretações do Brasil
  navbar:
    right:
      - href: pessoas.qmd
        text: Pessoas
      - href: publicacoes.qmd
        text: Publicações
      - href: contato.qmd
        text: Contato
  page-footer: 
    left: "Copyright 2022, Eduardo Dimitrov" 
    # right: 
    #   - text: UnB
    #   - href: https://www.unb.br

  
format:
  html:
    theme: litera
    mainfont: heuristica
    css: styles.css
    toc: true
    lang: pt-BR



